export {default as ResourcesIcon} from './Resources-icon'
export {default as SurveyIcon} from './Survey-icon'
export {default as DictionaryIcon} from './Dictionary-icon'
export {default as Cases} from './Cases-icon'
export {default as AboutIcon} from './About-icon'
export {default as ContactIcon} from './Contact-icon'
export {default as HomeIcon} from './Home-icon'
export {default as SidebarWave} from './SidebarWave'